### ISSUE TITLE
esbuild version used incompatible with apple arm

### ISSUE THREAD

**Issue by aslak01** [sveltech/ssr#12]
Installing fails at esbuild:

```node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild: Running postinstall script, failed in 34ms
.../esbuild@0.7.22/node_modules/esbuild postinstall$ node install.js
│ Unsupported platform: darwin arm64 LE
└─ Failed in 34ms
 ERROR  Command failed with exit code 1.
``` 

Please add support for the apple arm native version recently released: https://github.com/evanw/esbuild/pull/820

**Comment by jakobrosenberg** [comment]
Could you check if this is working in `tossr` `1.4.2`? 🙂

**Comment by aslak01** [comment]
Yep, it works.

**Comment by aslak01** [comment]
Hey, is it possible that the new version broke compatibility with Vercel? Trying to debug my build and I get this from Vercel's build log:


```js
15:02:21.401 | Trying to install "esbuild-linux-64" using npm
-- | --
15:02:21.402 | Failed to install "esbuild-linux-64" using npm: EACCES: permission denied, mkdir '/vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/esbuild-b65xq8s3hxn'
15:02:21.403 | Trying to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.8.54.tgz"
15:02:21.531 | /vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/install.js:203
15:02:21.531 | throw e;
15:02:21.531 | ^
15:02:21.531 | Error: EACCES: permission denied, open '/vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/bin/esbuild'
15:02:21.531 | at Object.openSync (fs.js:476:3)
15:02:21.531 | at Object.writeFileSync (fs.js:1467:35)
15:02:21.531 | at /vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/install.js:66:8
15:02:21.531 | at Generator.next (<anonymous>)
15:02:21.531 | at fulfilled (/vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/install.js:6:24)
15:02:21.531 | at processTicksAndRejections (internal/process/task_queues.js:93:5) {
15:02:21.532 | errno: -13,
15:02:21.532 | syscall: 'open',
15:02:21.532 | code: 'EACCES',
15:02:21.532 | path: '/vercel/.npm/_npx/707/lib/node_modules/spank/node_modules/esbuild/bin/esbuild'
15:02:21.532 | }
15:02:21.966 | npm ERR! code ELIFECYCLE
15:02:21.966 | npm ERR! errno 1
15:02:21.970 | npm ERR! esbuild@0.8.54 postinstall: `node install.js`
15:02:21.970 | npm ERR! Exit status 1
15:02:21.970 | npm ERR!
15:02:21.970 | npm ERR! Failed at the esbuild@0.8.54 postinstall script.


```

**Comment by aslak01** [comment]
Never mind that appears to be an issue related to how Vercel handles building files. I was able to build my project on netlify, but there are some files that aren't getting found when built.

**Comment by jakobrosenberg** [comment]
Very strange. I have the opposite experience. I never got it to work on netlify, but vercel is fine.
