### ISSUE TITLE
tossr sometimes runs out of memory in dev mode

### ISSUE THREAD

**Issue by mizzao** [sveltech/ssr#15]
I'll often see things like this when navigating around. It can happen even a few pages after starting `npm run dev:ssr`.

```
Unhandled promise rejection:
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:618:9)
    at Object.spawnWithSignal (node:child_process:761:17)
    at startService (/home/mao/parsnip/cookwithme/node_modules/esbuild/lib/main.js:748:29)
    at build (/home/mao/parsnip/cookwithme/node_modules/esbuild/lib/main.js:687:10)
    at inlineScript (/home/mao/parsnip/cookwithme/node_modules/tossr/tossr.js:111:15)
    at tossr (/home/mao/parsnip/cookwithme/node_modules/tossr/tossr.js:70:43)
    at /home/mao/parsnip/cookwithme/node_modules/spassr/src/spassr.js:38:28
    at Layer.handle [as handle_request] (/home/mao/parsnip/cookwithme/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mao/parsnip/cookwithme/node_modules/express/lib/router/route.js:137:13) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
Unhandled promise rejection:
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:618:9)
    at Object.spawnWithSignal (node:child_process:761:17)
    at startService (/home/mao/parsnip/cookwithme/node_modules/esbuild/lib/main.js:748:29)
    at build (/home/mao/parsnip/cookwithme/node_modules/esbuild/lib/main.js:687:10)
    at inlineScript (/home/mao/parsnip/cookwithme/node_modules/tossr/tossr.js:111:15)
    at tossr (/home/mao/parsnip/cookwithme/node_modules/tossr/tossr.js:70:43)
    at /home/mao/parsnip/cookwithme/node_modules/spassr/src/spassr.js:38:28
    at Layer.handle [as handle_request] (/home/mao/parsnip/cookwithme/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mao/parsnip/cookwithme/node_modules/express/lib/router/route.js:137:13) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
```

I guess it doesn't matter on the serverless side because each render only runs once, but it seems worrisome that something might have a memory leak.

**Comment by jakobrosenberg** [comment]
Good catch. Do you know if you're using `inlineDynamicImports`?

Regardless, I don't think this is an issue outside of `dev` where a new app is loaded (and possibly bundled inside `tossr`) for every file change. It would be great to solve it though.

**Comment by mizzao** [comment]
Yep, here's the relevant part of `serve()`:

```js
    // Default SSR to port 5000 so all account/cookie info remains the same as the nollup version,
    // allowing for a closer test of reality
    spassr({
      ...options,
      ssr: true,
      port: 5000,
      ssrOptions: { inlineDynamicImports: true, dev: true },
    });
    // SPA on 5005 as a backup. Might be able to just remove it.
    spassr({ ...options, port: 5005 });
```

**Comment by jakobrosenberg** [comment]
https://github.com/roxiness/tossr/blob/master/tossr.js#L111-L119

I wonder if `esbuild` has a memory leak or if the return from `inlineScript` isn't flushed between file changes. It could be cached.

**Comment by mizzao** [comment]
I think this might have actually been from my computer having a bad RAM stick. It was causing OOM errors in other applications as well. I'm going to close this unless I see it again.
