### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by LuvbCa** [sveltech/ssr#17]
when i try to make a request to an express server tossr prints : 
```
[0] [tossr] url: /
[0] [tossr] Error: SyntaxError: Unexpected token 'export'
[0]     at errorHandler (C:\Users\User\Documents\unnamedChatApp\client\breed\node_modules\tossr\tossr.js:22:15)
[0]     at C:\Users\User\Documents\unnamedChatApp\client\breed\node_modules\tossr\tossr.js:107:25
[0]     at processTicksAndRejections (node:internal/process/task_queues:94:5)
[0] [tossr] Error on url: /
[0] [tossr] Unhandled promise rejection:
[0] [tossr] / Waited for the event "app-loaded", but timed out after 5000 ms.
[0] [tossr] / - 5027ms 
```

my Question now is why tossr prints that because it doesn't make sense. Also im using Routify and Rollup 

relevant files? -> [rollup.config.js](https://pastebin.com/4Amv1eRL), [__app.html](https://pastebin.com/fL34SMmh)

Thanks in advance :)

**Comment by jakobrosenberg** [comment]
Can't tell what's causing this. Are you using the Routify starter template?

**Comment by LuvbCa** [comment]
yes but i modified my package.json, because im using my own server based on express -> [server.ts](https://pastebin.com/y8Sws6Nb), and i just commented out the spassr lines from the rollup.config.js. I looked in the spassr source files how the tossr server is created but i do it just the same way, so i am confused

**Comment by LuvbCa** [comment]
i figured it out. i needed to enable inlineDynamicImports. But thanks anyways :)
